<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit36c9e99e0004f18e91a249d99b06c730
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit36c9e99e0004f18e91a249d99b06c730::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit36c9e99e0004f18e91a249d99b06c730::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit36c9e99e0004f18e91a249d99b06c730::$classMap;

        }, null, ClassLoader::class);
    }
}
